name: 'snowflake_tpch_demo'   # Your dbt project name
version: '1.0.0'
config-version: 2

# This tells dbt which profile to use for your Snowflake connection
profile: 'default'

# Paths for models, seeds, snapshots, etc.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Where dbt stores compiled SQL
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configure models
models:
  snowflake_tpch_demo:
    +database: DEV_DB        # Your target database for models
    +schema: DEV_SCHEMA      # Schema in DEV_DB where models will be created
