version: 2
models:
  - name: stg_orders
    columns:
      - name: ORDER_KEY
        tests:
          - not_null
          - unique
  - name: customer_revenue
    columns:
      - name: CUSTOMER_KEY
        tests:
          - not_null
