version: 2
models:
  - name: stg_orders
    columns:
      - name: ORDER_KEY
        tests:
          - not_null
          - unique
  - name: customer_revenue
    columns:
      - name: CUSTOMER_KEY
        tests:
          - not_null
      - name: total_revenue
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "total_revenue >= 0"
